### ISSUE TITLE
Add `Identity` as default encoder for Service. 

### ISSUE THREAD

**Issue by koaning** [koaning/simsity#14]
As mentioned in https://github.com/koaning/simsity/pull/13:

> I think the refit parameter should go in the Service() call. I think there should also be a parameter somewhere to avoid calling .transform() if the data has already been transformed. Do you think it is worth adding an additional parameter to Service() and keeping the indexed_from_transformed_data method?

It's a fair remark. I think preventing a `transfrom()` is fair, but the solution would be to have an `Identity()` transformer that just keeps the data as-is. This would also make a great default value for the encoder. 

Made this issue to track progress and to discuss the approach.

**Comment by gclen** [comment]
I think the Identity transformer is a good idea (and I would be willing to submit a PR for it). One question I have is training on objects that are not pandas dataframes. For example I think a lot of data passed in will be numpy arrays or scipy matrices. Is it worth having the two training methods (```train_from_dataf``` and a more general one)?

**Comment by koaning** [comment]
There's certainly something to be said for a general `train` method but it's very early days for the project (as in, it's barely a week old). It, therefore, felt safe not to assume anything about the general use case yet while I am still receiving initial feedback. 

A key benefit of using data frames, for now, is that it keeps things simple.
