### ISSUE TITLE
Update indexer

### ISSUE THREAD

**Issue by nthomsencph** [koaning/simsity#28]
Hi! Are there any plans to add support for updating the indexer, i.e. add new documents without retraining the entire pipeline? Would be a very useful feature . 

``` python
from simsity.service import Service

service = Service(
    indexer=indexer,
    encoder=encoder
)

service.train_from_dataf(df, features=["text"])

....

service.update(new_docs, features=["text"])  # <- this

```

**Comment by koaning** [comment]
I contemplated this for a moment but both [annoy](https://github.com/spotify/annoy) and PyNNDescent don't support this. To quote the readme on annoy: 

> `a.build(n_trees, n_jobs=-1)` builds a forest of n_trees trees. More trees gives higher precision when querying. After calling build, no more items can be added. n_jobs specifies the number of threads used to build the trees. n_jobs=-1 uses all available CPU cores.

I've also noticed that this is a use-case that I've never really needed. It's a rapid prototyping tool and you can always build the index from scratch if need be.
